/**
 * AIBadgeWithPopover - AI badge with contextual information
 * 
 * Shows confidence score, detection type, and helpful context
 */

'use client'

import { Sparkles, Info } from 'lucide-react'
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from '@/components/ui/hover-card'
import { cn } from '@/lib/utils/cn'

interface AIBadgeWithPopoverProps {
  confidence?: number
  aiType?: 'generated' | 'enhanced' | 'detected' | 'calculated'
  fieldName?: string
  detectionDetails?: string
  className?: string
}

export function AIBadgeWithPopover({
  confidence = 0.95,
  aiType = 'detected',
  fieldName,
  detectionDetails,
  className
}: AIBadgeWithPopoverProps) {
  // Handle both decimal (0.85) and percentage (85) formats
  const normalizedConfidence = confidence > 1 ? confidence / 100 : confidence
  const confidencePercent = Math.round(normalizedConfidence * 100)
  
  const aiTypeLabels = {
    generated: 'AI Generated',
    enhanced: 'AI Enhanced',
    detected: 'AI Detected',
    calculated: 'AI Calculated'
  }

  const aiTypeDescriptions = {
    generated: 'This value was generated by AI based on available data',
    enhanced: 'This value was enhanced by AI for better accuracy',
    detected: 'This value was detected by AI from your receipt image',
    calculated: 'This value was calculated automatically based on other fields'
  }

  const confidenceColor = 
    confidencePercent >= 90 ? 'text-green-600' :
    confidencePercent >= 75 ? 'text-yellow-600' :
    'text-orange-600'

  const confidenceLabel =
    confidencePercent >= 90 ? 'High confidence' :
    confidencePercent >= 75 ? 'Medium confidence' :
    'Low confidence'

  return (
    <HoverCard openDelay={200} closeDelay={100}>
      <HoverCardTrigger asChild>
        <button
          className={cn(
            "inline-flex items-center gap-1 px-1.5 py-0.5 rounded",
            "bg-purple-50 text-purple-600 text-xs font-medium",
            "hover:bg-purple-100 transition-colors cursor-help",
            "flex-shrink-0",
            className
          )}
        >
          <Sparkles className="w-3 h-3" />
          AI
        </button>
      </HoverCardTrigger>
      <HoverCardContent className="w-80" align="end">
        <div className="space-y-3">
          {/* Header */}
          <div className="flex items-start gap-2">
            <div className="p-2 bg-purple-100 rounded-lg">
              <Sparkles className="w-4 h-4 text-purple-600" />
            </div>
            <div className="flex-1">
              <h4 className="font-semibold text-sm text-gray-900">
                {aiTypeLabels[aiType]}
              </h4>
              <p className="text-xs text-gray-600 mt-0.5">
                {aiTypeDescriptions[aiType]}
              </p>
            </div>
          </div>

          {/* Confidence Score */}
          {aiType !== 'calculated' && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs">
                <span className="text-gray-600">Confidence</span>
                <span className={cn("font-semibold", confidenceColor)}>
                  {confidencePercent}% · {confidenceLabel}
                </span>
              </div>
              <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                <div
                  className={cn(
                    "h-full rounded-full transition-all",
                    confidencePercent >= 90 ? "bg-green-500" :
                    confidencePercent >= 75 ? "bg-yellow-500" :
                    "bg-orange-500"
                  )}
                  style={{ width: `${confidencePercent}%` }}
                />
              </div>
            </div>
          )}

          {/* Detection Details */}
          {detectionDetails && (
            <div className="pt-2 border-t border-gray-100">
              <div className="flex items-start gap-2">
                <Info className="w-3.5 h-3.5 text-gray-400 mt-0.5 flex-shrink-0" />
                <p className="text-xs text-gray-600 leading-relaxed">
                  {detectionDetails}
                </p>
              </div>
            </div>
          )}

          {/* Low Confidence Warning */}
          {confidencePercent < 75 && (
            <div className="pt-2 border-t border-gray-100">
              <div className="flex items-start gap-2 p-2 bg-yellow-50 rounded-lg">
                <Info className="w-3.5 h-3.5 text-yellow-600 mt-0.5 flex-shrink-0" />
                <p className="text-xs text-yellow-800">
                  Please verify this value for accuracy
                </p>
              </div>
            </div>
          )}

          {/* Footer Tip */}
          <div className="pt-2 border-t border-gray-100">
            <p className="text-xs text-gray-500">
              💡 You can edit any AI-detected field by clicking on it
            </p>
          </div>
        </div>
      </HoverCardContent>
    </HoverCard>
  )
}
